### ISSUE TITLE
psutil.NoSuchProcess: process no longer exists

### ISSUE THREAD

**Issue by purplespider** [RhetTbull/RepairPhotosBookmarks#3]
Struggling to get past this error when running:

````bash
WARNING: this program will rewrite your Photos library database and could result in total data loss.
Please ensure you have a backup and that the Photos app is not running!
Do you want to proceed? [y/N]: y
Please open Photos and uncheck the box 'Importing: Copy items to the Photos library' in Photos Preferences.
Type 'y' when you have done this. [y/N]: y
Please quit Photos.
Type 'y' when you have done this. [y/N]: y
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 343, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 401, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(KERN_PROCARGS2) -> EINVAL)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/james/Downloads/RepairPhotosBookmarks-main/repair_photos_bookmarks.py", line 356, in <module>
    main()
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/james/Downloads/RepairPhotosBookmarks-main/repair_photos_bookmarks.py", line 249, in main
    while photos_is_running():
  File "/Users/james/Downloads/RepairPhotosBookmarks-main/repair_photos_bookmarks.py", line 46, in photos_is_running
    return any(p.name() == "Photos" for p in psutil.process_iter())
  File "/Users/james/Downloads/RepairPhotosBookmarks-main/repair_photos_bookmarks.py", line 46, in <genexpr>
    return any(p.name() == "Photos" for p in psutil.process_iter())
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 628, in name
    cmdline = self.cmdline()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 681, in cmdline
    return self._proc.cmdline()
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 348, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=27506)
````

I'm on an M1 Mac Studio. Any pointers appreciated.

**Comment by RhetTbull** [comment]
Hi @purplespider Not sure about this specific error and I don't have access to an M1 Mac for testing. Try this then re-run: `python3 -m pip install --upgrade psutil` and see if that helps.  

By the way, this script is highly experimental so please make sure you have a backup before proceeding.  I am working on incorporating some updates from @dgleich and rolling this into another project of mine that does much more with Photos called [osxphotos](https://github.com/RhetTbull/osxphotos). I suggest you try to run the `repair_photos_bookmarks_dgleich.py` version which includes David's changes once we figure out the psutil issue.

**Comment by purplespider** [comment]
Thanks, @RhetTbull. No joy with that, unfortunately, but I've been able to run it fine on a non-M1 Mac.

Although I've since discovered it doesn't quite help for my use case. I have a Photos library that was originally an iPhoto library with half the photos were referenced and while I still have the folder of images, the link to them is now broken as they're no longer on the same volume. But it seems that this script reads and updates the ZBOOKMARKDATA blob and I was hoping it would be able to write missing ZBOOKMARKDATA blobs from the path data, as because this library came from iPhoto there is no existing ZBOOKMARKDATA data.

But don't worry, I'll explore further options. Thanks for your time on this script though!

**Comment by RhetTbull** [comment]
@purplespider the code that's failing on M1 is only used to determine if Photos is still running (it's important that Photos is not running during part of the execution of RepairPhotosBookmarks).  Could you try the following while Photos is running on your M1 mac and let me know if you get any output?

```
ps -ax -o command | grep Applications/Photos.app/Contents/MacOS/Photos | grep -v grep
```

I expect it to print: `/System/Applications/Photos.app/Contents/MacOS/Photos`

**Comment by RhetTbull** [comment]
I'm not able to test on M1 but I believe this will correctly determine if Photos is running without using `psutil` library which is what's causing the crash:

```python
def photos_is_running() -> bool:
    """Returns True if Photos is running"""
    output = (
        subprocess.check_output(["ps", "-ax", "-o", "command"])
        .decode("utf-8")
        .splitlines()
    )
    return any(cmd.endswith("Photos.app/Contents/MacOS/Photos") for cmd in output)
```

**Comment by purplespider** [comment]
> I expect it to print: `/System/Applications/Photos.app/Contents/MacOS/Photos`

Yep, that's performing as expected on an M1!

I'll get back to you on those other two. Thanks so much for looking into this.

**Comment by purplespider** [comment]
> Assuming there's data in the 5th column (ZPATHRELATIVETOVOLUME) then I believe the bookmarks can be reconstructed.

Yep, the correct paths display for me!

I've actually managed to resolve this a different way. (I had an old macOS 10.14 virtual machine in Parallels, installed Aperture on it, opened the Photos library in Aperture and used its "relocate" feature to fix the broken links, I then used it's consolidate function as this seems to be much more robust than the one in Photos. Now the old library is ready to import into my main Photos library. But I do appreciate your time considering an alternative solution for this. I'll keep the broken copy of the library around for testing if you still decide to add this function.

----

> I'm not able to test on M1 but I believe this will correctly determine if Photos is running without using `psutil` library

Just tried this, but get `subprocess' is not defined`:

````
Please quit Photos.
Type 'y' when you have done this. [y/N]: y
Traceback (most recent call last):
  File "/Users/james/Downloads/_Other/RepairPhotosBookmarks-main/repair_photos_bookmarks_dgleich.py", line 517, in <module>
    main()
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/james/Downloads/_Other/RepairPhotosBookmarks-main/repair_photos_bookmarks_dgleich.py", line 367, in main
    while photos_is_running() and restart==False:
  File "/Users/james/Downloads/_Other/RepairPhotosBookmarks-main/repair_photos_bookmarks_dgleich.py", line 56, in photos_is_running
    user_name = subprocess.check_output(["id", "-un"]).decode("utf-8").strip()
NameError: name 'subprocess' is not defined
````

**Comment by purplespider** [comment]
> subprocess' is not defined

Ah, hold on let me try and import it! 🤦🏻‍♂️

**Comment by purplespider** [comment]
> I'm not able to test on M1 but I believe this will correctly determine if Photos is running without using `psutil` library which is what's causing the crash

Yep, I can confirm this appears to fix the issue and the scripts now gets all the way through on an M1 Mac. 🚀

**Comment by RhetTbull** [comment]
Great--thanks for the additional data and glad you got your library fixed. I'm still going to take a hack at a fixing this script to work.  I think it'll be relatively easy to do and may help others down the road.
